# Set the version to 2
version: '2'
# This empty directory is where you should create a docker-compose.yml
services:
  drupal:
    # Use the drupal:8.8.2 image along with the postgres:12.1 image
    image: drupal:8.8.2
    # Walk through Drupal config in browser at http://localhost:8080
    # Use ports to expose Drupal on 8080
    ports:
      - '8080:80'

  postgres:
    image: postgres:12.1
    environment:
      # Be sure to setup POSTGRES_PASSWORD on postgres image
      POSTGRES_DB: drupal
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: somepassword

# Tip: Drupal assumes DB is localhost, but it will actually be on the compose service name you give it
# Use Docker Hub documentation to figure out the right environment and volume settings
# Extra Credit: Use volumes to store Drupal unique data






